import type { Component } from 'vue';
import {
  ArrowRightToLine,
  AtSign,
  Check,
  ChevronsUpDown,
  CircleX,
  ClipboardPaste,
  Code,
  Columns2,
  Copy,
  CopyX,
  Eraser,
  Eye,
  File,
  FilePlus,
  FileText,
  Filter,
  FilterX,
  FolderMinus,
  FolderOpen,
  FolderPlus,
  FolderSearch,
  GitCompare,
  ListTree,
  Maximize2,
  MessageSquare,
  Palette,
  PanelBottom,
  PanelRight,
  Pencil,
  PencilLine,
  Plus,
  Replace,
  ReplaceAll,
  RotateCw,
  ScrollText,
  Search,
  Shapes,
  ShieldCheck,
  Square,
  SquareCode,
  Tag,
  Tags,
  TextSelect,
  Trash2,
  Ungroup,
  X,
} from 'lucide-vue-next';
import type { OverlayIcon } from '../../preload/overlay-channels';

export const OVERLAY_ICON_COMPONENTS: Readonly<Record<OverlayIcon, Component>> = {
  'arrow-right-to-line': ArrowRightToLine,
  'at-sign': AtSign,
  check: Check,
  'chevrons-up-down': ChevronsUpDown,
  'circle-x': CircleX,
  'clipboard-paste': ClipboardPaste,
  code: Code,
  'columns-2': Columns2,
  copy: Copy,
  'copy-x': CopyX,
  eraser: Eraser,
  eye: Eye,
  file: File,
  'file-plus': FilePlus,
  'file-text': FileText,
  filter: Filter,
  'filter-x': FilterX,
  'folder-minus': FolderMinus,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  'folder-search': FolderSearch,
  'git-compare': GitCompare,
  'list-tree': ListTree,
  'maximize-2': Maximize2,
  'message-square': MessageSquare,
  palette: Palette,
  'panel-bottom': PanelBottom,
  'panel-right': PanelRight,
  pencil: Pencil,
  'pencil-line': PencilLine,
  plus: Plus,
  replace: Replace,
  'replace-all': ReplaceAll,
  'rotate-cw': RotateCw,
  'scroll-text': ScrollText,
  search: Search,
  shapes: Shapes,
  'shield-check': ShieldCheck,
  square: Square,
  'square-code': SquareCode,
  tag: Tag,
  tags: Tags,
  'text-select': TextSelect,
  'trash-2': Trash2,
  ungroup: Ungroup,
  x: X,
};
