const PHP_EXTERNAL_PATTERNS: RegExp[] = [
	/^Illuminate\\/,
	/^Carbon\\/,
	/^League\\/,
	/^Symfony\\/,
	/^Laravel\\/,
	/^Doctrine\\/,
	/^Monolog\\/,
	/^Ramsey\\/,
	/^Psr\\/,
	/^GuzzleHttp\\/,
	/^Faker\\/,
	/^PHPUnit\\/,
	/^Mockery\\/,
	/^React\\/,
	/^Nette\\/,
	/^Predis\\/,
	/^Firebase\\/,
	/^Spatie\\/,
	/^Inertia\\/,
	/^Tightenco\\/,
	/^Livewire\\/,
	/^Barryvdh\\/,
	/^Maatwebsite\\/,
	/^Nyholm\\/,
	/^Opcodes\\/,
	/^Ratchet\\/,
	/^Filament\\/,
	/^Intervention\\/,
	/^Twilio\\/,
	/^Kreait\\/,
	/^Pusher\\/,
];

const PHP_BUILTIN_TYPES = new Set([
	'Exception', 'RuntimeException', 'InvalidArgumentException', 'LogicException',
	'TypeError', 'ValueError', 'Error', 'stdClass', 'Closure', 'Generator',
	'Throwable', 'Stringable', 'JsonSerializable', 'ArrayAccess', 'Countable',
	'Iterator', 'Serializable', 'Traversable',
	'BadMethodCallException', 'DomainException', 'OverflowException',
	'UnexpectedValueException', 'LengthException', 'OutOfRangeException',
	'RangeException', 'BadFunctionCallException', 'UnderflowException',
	'OutOfBoundsException', 'ArithmeticError', 'DivisionByZeroError',
	'IteratorAggregate', 'SplObserver', 'SplSubject',
	'SplHeap', 'SplStack', 'SplQueue', 'SplPriorityQueue',
	'SplFixedArray', 'SplObjectStorage', 'SplFileInfo', 'SplFileObject',
	'PDO', 'PDOStatement', 'PDOException',
	'DateTime', 'DateTimeImmutable', 'DateTimeInterface', 'DateInterval', 'DateTimeZone',
	'BackedEnum', 'UnitEnum',
	'ReflectionClass', 'ReflectionMethod', 'ReflectionProperty', 'ReflectionFunction',
	'ReflectionParameter', 'ReflectionType', 'ReflectionNamedType', 'ReflectionException',
	'CurlHandle', 'CurlMultiHandle',
]);

const TS_BUILTIN_TYPES = new Set([
	'Omit', 'Partial', 'Pick', 'Record', 'Exclude', 'Extract', 'Required', 'Readonly',
	'ReturnType', 'Parameters', 'InstanceType', 'NonNullable', 'Awaited',
	'ConstructorParameters', 'ThisParameterType', 'OmitThisParameter', 'ThisType',
	'Uppercase', 'Lowercase', 'Capitalize', 'Uncapitalize',
	'Promise', 'PromiseLike', 'Array', 'ArrayLike', 'Map', 'Set', 'WeakMap', 'WeakSet',
	'RegExp', 'Date', 'Error', 'Buffer', 'Symbol', 'BigInt',
	'Iterable', 'AsyncIterable', 'Iterator', 'AsyncIterator',
	'Generator', 'AsyncGenerator',
	'HTMLElement', 'HTMLDivElement', 'HTMLInputElement', 'HTMLButtonElement',
	'HTMLFormElement', 'HTMLImageElement', 'HTMLAnchorElement', 'HTMLSelectElement',
	'HTMLTextAreaElement', 'HTMLCanvasElement', 'HTMLVideoElement', 'HTMLAudioElement',
	'HTMLSpanElement', 'SVGElement', 'SVGSVGElement',
	'Element', 'Event', 'Document', 'Node', 'EventTarget', 'NodeList', 'HTMLCollection',
	'Window', 'Navigator', 'Location', 'History', 'Storage',
	'CSSStyleDeclaration', 'DOMRect', 'DOMRectReadOnly', 'DOMTokenList',
	'MutationObserver', 'IntersectionObserver', 'ResizeObserver', 'PerformanceObserver',
	'MutationRecord', 'IntersectionObserverEntry', 'ResizeObserverEntry',
	'MouseEvent', 'KeyboardEvent', 'FocusEvent', 'InputEvent', 'TouchEvent',
	'DragEvent', 'PointerEvent', 'WheelEvent', 'AnimationEvent', 'TransitionEvent',
	'ClipboardEvent', 'CustomEvent', 'MessageEvent', 'UIEvent', 'CompositionEvent',
	'SubmitEvent', 'ProgressEvent', 'PopStateEvent', 'StorageEvent',
	'Response', 'Request', 'Headers', 'URL', 'URLSearchParams',
	'AbortController', 'AbortSignal',
	'FormData', 'Blob', 'FileReader', 'FileList',
	'ReadableStream', 'WritableStream', 'TransformStream',
	'TextEncoder', 'TextDecoder',
	'WebSocket', 'XMLHttpRequest',
	'Worker', 'SharedWorker', 'ServiceWorker',
	'MediaStream', 'MediaRecorder',
	'CanvasRenderingContext2D', 'WebGLRenderingContext', 'WebGL2RenderingContext',
	'ArrayBuffer', 'SharedArrayBuffer', 'DataView',
	'Int8Array', 'Uint8Array', 'Uint8ClampedArray',
	'Int16Array', 'Uint16Array', 'Int32Array', 'Uint32Array',
	'Float32Array', 'Float64Array', 'BigInt64Array', 'BigUint64Array',
	'NodeJS',
]);

export function isKnownExternal(target: string): boolean {
	if (PHP_EXTERNAL_PATTERNS.some(p => p.test(target))) return true;
	if (PHP_BUILTIN_TYPES.has(target)) return true;
	if (TS_BUILTIN_TYPES.has(target)) return true;
	if (target.startsWith('node_modules/') || target.startsWith('node_modules\\')) return true;
	if (target.startsWith('vendor/') || target.startsWith('vendor\\')) return true;
	if (/[/\\]node_modules[/\\]/.test(target) || /[/\\]vendor[/\\]/.test(target)) return true;
	return false;
}
