import { describe, it, expect } from 'vitest';
import { AGENT_PROFILES, AGENT_PROFILE_MAP } from '../agent-profiles.generated';

// This file is auto-generated by `npm run generate:profiles` from the curated `agent-profiles/`
// source tree. This test locks the team-mode specialist catalog to an exact mirror of the user's
// Claude Code subagent set (~/.claude/agents): 91 profiles across 8 divisions, governed by
// ~/.claude/scripts/sync-claude-agents.mjs (DEFAULT_DIVISIONS minus the EXCLUDE denylist, further
// narrowed per division by DIVISION_ALLOWLIST), which is itself mirrored by
// scripts/sync-agent-profiles.mjs.
//
// To change the catalog DELIBERATELY: edit the policy in scripts/sync-agent-profiles.mjs (and the
// matching ~/.claude/scripts/sync-claude-agents.mjs), run `npm run sync:profiles -- --apply --prune`
// then `npm run generate:profiles`, and update the pinned allowlist + counts below in the SAME
// commit. If this test fails unexpectedly, the catalog drifted from the intended 91-set.

const EXPECTED_CATEGORY_COUNTS: Record<string, number> = {
  Engineering: 36,
  Design: 9,
  Testing: 9,
  Specialized: 8,
  Security: 12,
  Product: 5,
  'Project Management': 7,
  // Partial mirror: 5 of game-development's 20 agents, per DIVISION_ALLOWLIST in both sync scripts.
  'Game Development': 5,
};

const EXPECTED_IDS = [
  'agents-orchestrator',
  'blender-addon-engineer',
  'design-brand-guardian',
  'design-image-prompt-engineer',
  'design-inclusive-visuals-specialist',
  'design-persona-walkthrough',
  'design-ui-designer',
  'design-ux-architect',
  'design-ux-researcher',
  'design-visual-storyteller',
  'design-whimsy-injector',
  'engineering-ai-data-remediation-engineer',
  'engineering-ai-engineer',
  'engineering-autonomous-optimization-architect',
  'engineering-backend-architect',
  'engineering-cms-developer',
  'engineering-code-reviewer',
  'engineering-codebase-onboarding-engineer',
  'engineering-data-engineer',
  'engineering-database-optimizer',
  'engineering-desktop-app-engineer',
  'engineering-devops-automator',
  'engineering-drupal-shopping-cart',
  'engineering-email-intelligence-engineer',
  'engineering-embedded-firmware-engineer',
  'engineering-feishu-integration-developer',
  'engineering-filament-optimization-specialist',
  'engineering-frontend-developer',
  'engineering-git-workflow-master',
  'engineering-i18n-engineer',
  'engineering-incident-response-commander',
  'engineering-it-service-manager',
  'engineering-minimal-change-engineer',
  'engineering-mobile-app-builder',
  'engineering-multi-agent-systems-architect',
  'engineering-orgscript-engineer',
  'engineering-prompt-engineer',
  'engineering-rapid-prototyper',
  'engineering-realtime-collaboration-engineer',
  'engineering-senior-developer',
  'engineering-software-architect',
  'engineering-solidity-smart-contract-engineer',
  'engineering-sre',
  'engineering-technical-writer',
  'engineering-voice-ai-integration-engineer',
  'engineering-wechat-mini-program-developer',
  'engineering-wordpress-shopping-cart',
  'game-audio-engineer',
  'game-designer',
  'level-designer',
  'product-behavioral-nudge-engine',
  'product-feedback-synthesizer',
  'product-manager',
  'product-sprint-prioritizer',
  'product-trend-researcher',
  'project-management-experiment-tracker',
  'project-management-jira-workflow-steward',
  'project-management-meeting-notes-specialist',
  'project-management-project-shepherd',
  'project-management-studio-operations',
  'project-management-studio-producer',
  'project-manager-senior',
  'security-ai-generated-code-auditor',
  'security-appsec-engineer',
  'security-architect',
  'security-blockchain-security-auditor',
  'security-cloud-security-architect',
  'security-compliance-auditor',
  'security-incident-responder',
  'security-penetration-tester',
  'security-secrets-credential-engineer',
  'security-senior-secops',
  'security-threat-detection-engineer',
  'security-threat-intelligence-analyst',
  'specialized-codebase-archaeologist',
  'specialized-document-generator',
  'specialized-mcp-builder',
  'specialized-model-qa',
  'specialized-pricing-analyst',
  'specialized-salesforce-architect',
  'specialized-workflow-architect',
  'technical-artist',
  'testing-accessibility-auditor',
  'testing-api-tester',
  'testing-evidence-collector',
  'testing-performance-benchmarker',
  'testing-reality-checker',
  'testing-test-automation-engineer',
  'testing-test-results-analyzer',
  'testing-tool-evaluator',
  'testing-workflow-optimizer',
];

// Profiles whose source .md uses section headers the generator's Identity/Mission/Rules patterns
// don't recognize, so the corresponding field generates empty. These are pre-existing upstream
// content-structure quirks (the profile still works, just with a thinner prompt), pinned here so the
// guardrail below catches any NEW empty section — e.g. a future header rename that silently drops a
// previously-populated identity/mission/rules. To clear an entry: fix the section header in the
// source .md (so the generator picks it up), regenerate, and remove it from this map in the same commit.
const KNOWN_EMPTY_SECTIONS: Record<string, ReadonlyArray<'identity' | 'mission' | 'rules'>> = {
  'engineering-senior-developer': ['mission'],
  'product-feedback-synthesizer': ['mission', 'rules'],
  'product-sprint-prioritizer': ['mission', 'rules'],
  'product-trend-researcher': ['mission', 'rules'],
};

describe('agent-profiles.generated — catalog locked to the 91-agent Claude Code set', () => {
  it('contains exactly 91 profiles', () => {
    expect(AGENT_PROFILES.length).toBe(91);
  });

  it('spans exactly the 8 expected categories', () => {
    const categories = new Set(AGENT_PROFILES.map(p => p.category));
    expect([...categories].sort()).toEqual(Object.keys(EXPECTED_CATEGORY_COUNTS).sort());
  });

  it('excludes the 6 removed divisions', () => {
    const categories = new Set(AGENT_PROFILES.map(p => p.category));
    for (const removed of [
      'Academic',
      'Marketing',
      'Paid Media',
      'Sales',
      'Spatial Computing',
      'Support',
    ]) {
      expect(categories.has(removed)).toBe(false);
    }
  });

  // Game Development is mirrored in PART. The category-count check above would still pass if an
  // engine-specific agent replaced an allowed one, so pin the exclusions the allowlist exists to make.
  it('admits no engine-specific game-development agent', () => {
    for (const excluded of [
      'godot-gameplay-scripter',
      'godot-multiplayer-engineer',
      'godot-shader-developer',
      'narrative-designer',
      'unity-architect',
      'unreal-systems-engineer',
      'roblox-systems-scripter',
    ]) {
      expect(AGENT_PROFILE_MAP.has(excluded)).toBe(false);
    }
  });

  it('matches the expected per-category counts', () => {
    const counts: Record<string, number> = {};
    for (const p of AGENT_PROFILES) counts[p.category] = (counts[p.category] ?? 0) + 1;
    expect(counts).toEqual(EXPECTED_CATEGORY_COUNTS);
  });

  it('matches the pinned 91-ID allowlist exactly', () => {
    const ids = AGENT_PROFILES.map(p => p.id).sort();
    expect(ids).toEqual([...EXPECTED_IDS].sort());
  });

  it('exposes all 91 profiles via AGENT_PROFILE_MAP and drops removed IDs', () => {
    expect(AGENT_PROFILE_MAP.size).toBe(91);
    expect(AGENT_PROFILE_MAP.has('marketing-seo-specialist')).toBe(false);
  });

  it('populates identity/mission/rules except for the pinned known-empty sections', () => {
    const actualEmpty: Record<string, string[]> = {};
    for (const p of AGENT_PROFILES) {
      const empties = (['identity', 'mission', 'rules'] as const).filter(f => p[f].trim() === '');
      if (empties.length) actualEmpty[p.id] = empties;
    }
    expect(actualEmpty).toEqual(KNOWN_EMPTY_SECTIONS);
  });
});
