import type { ModelInfo } from './settings';

export const FEEDBACK_MARKER = "The user provided the following reason for the rejection:";
export const DEFAULT_THINKING_TOKENS = 63999;
export const DEFAULT_CONTEXT_WINDOW = 200_000;
export const DEFAULT_FALLBACK_MODEL = "claude-opus-4-8";

export const DEFAULT_MODELS: ModelInfo[] = [
  {
    value: "claude-opus-4-8",
    displayName: "Opus 4.8",
    description: "Most capable model for agentic work",
    contextWindow: 1_000_000,
    supportsAdaptiveThinking: true,
    supportsEffort: true,
    supportedEffortLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
    supportsFastMode: true,
    supportsAutoMode: true,
    alwaysUses1mContext: true,
  },
  {
    value: "claude-sonnet-4-6",
    displayName: "Sonnet 4.6",
    description: "Best balance of speed and capability",
    contextWindow: 200_000,
    supportsAdaptiveThinking: true,
    supportsEffort: true,
    supportedEffortLevels: ['low', 'medium', 'high', 'max'],
    supportsFastMode: true,
    supportsAutoMode: true,
  },
  {
    value: "claude-haiku-4-5-20251001",
    displayName: "Haiku 4.5",
    description: "Fastest model",
    contextWindow: 200_000,
  },
  {
    value: "gpt-5.5",
    displayName: "GPT-5.5",
    description: "Frontier model for complex coding, research, and real-world work",
    contextWindow: 400_000,
    supportsAdaptiveThinking: true,
    supportsEffort: true,
    supportedEffortLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
    backend: "openai",
    openaiModelId: "gpt-5.5",
    openaiAuthMode: "any",
    openaiReasoningEffort: "medium",
  },
  {
    value: "gpt-5.4",
    displayName: "GPT-5.4",
    description: "Strong model for everyday coding",
    contextWindow: 256_000,
    supportsAdaptiveThinking: true,
    supportsEffort: true,
    supportedEffortLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
    backend: "openai",
    openaiModelId: "gpt-5.4",
    openaiAuthMode: "any",
    openaiReasoningEffort: "none",
  },
  {
    value: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini",
    description: "Small, fast, and cost-efficient model for simpler coding tasks",
    contextWindow: 128_000,
    supportsAdaptiveThinking: true,
    supportsEffort: true,
    supportedEffortLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
    backend: "openai",
    openaiModelId: "gpt-5.4-mini",
    openaiAuthMode: "any",
    openaiReasoningEffort: "medium",
  },
  {
    value: "gpt-5.3-codex",
    displayName: "GPT-5.3 Codex",
    description: "Coding-optimized model",
    contextWindow: 200_000,
    supportsAdaptiveThinking: true,
    supportsEffort: true,
    supportedEffortLevels: ['low', 'medium', 'high', 'xhigh'],
    backend: "openai",
    openaiModelId: "gpt-5.3-codex",
    openaiAuthMode: "any",
    openaiReasoningEffort: "high",
  },
  {
    value: "gpt-5.2",
    displayName: "GPT-5.2",
    description: "Earlier-generation general-purpose model",
    contextWindow: 200_000,
    supportsAdaptiveThinking: true,
    supportsEffort: true,
    supportedEffortLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
    backend: "openai",
    openaiModelId: "gpt-5.2",
    openaiAuthMode: "any",
    openaiReasoningEffort: "none",
  },
];
